#lang racket
(define (valorDeBolsa)
  (define coinA 0)
  (define coinB 0)
  (define coinC 0)
  (define coinD 0)
  (define coinE 0)
  (display "Programa para calcular el valor de una bolsa de monedas para el supermercado ''El ahorrito''")
  (display "Por favor introduzca el número de monedas de 20: ")
  (set! coinA (read))
  (display "Por favor introduzca el número de monedas de 50: ")
  (set! coinB (read))
  (display "Por favor introduzca el número de monedas de 100: ")
  (set! coinC (read))
  (display "Por favor introduzca el número de monedas de 200: ")
  (set! coinD (read))
  (display "Por favor introduzca el número de monedas de 500: ")
  (set! coinE (read))
  (display "El valor total de todas las monedas es: ")
  (display (calculo coinA coinB coinC coinD coinE))
  )

(define (calculo a b c d e)
  (+ (* a 20) (* b 50) (* c 100) (* d 200) (* e 500))
)
