#lang racket
;Ejercicio 1
(define (fallosEquipo)
  (define x 0) 
  (display "Programa para expresar la falla y la solución del computador, escriba un numero entre 1-3
  ")
  (set! x (read))
  (cond 
    ((= x 1) (display "El computador no enciende. Revise Conexión"))
    ((= x 2) (display "El computador se bloquea después de 10 minutos. Vacunar equipo."))
    ((= x 3) (display "El computador se bloquea cuando abro varias aplicaciones. Aumentar capacidad de memoria."))
    (else (display "El número digitado no es posible identificarlo"))
    )
  )

;Ejercicio 2
(define (NumerosSemejantes)
  (define x 0)
  (define y 0) 
  (display "Escribe el primer numero: ")
  (set! x (read))
  (display "Escribe el segundo numero: ")
  (set! y (read))
  (cond
    ((> x y) (begin (display "El numero mayor es: ")(display x)))
    ((< x y) (begin (display "el numero mayor es: ")(display y)))
    ((= x y) (display "los numeros son iguales"))
    (else (display "Valor no valido"))
    )
  )

;Ejercicio 3
(define (AlmacenHarina)
  (define x 0)
  (display "Cuanta harina en Kg comprara: ")
  (set! x (read))
  (display "El total de harina en Kg a empacar es de: ")
  (funcion x)
  )
(define (funcion x)
  (if (<= x 10)
      (display x)
      (if (<= x 100)
          (+ x 3)
          (if (<= x 500)
              (+ x(* x 0.10))
              (display"")
              )
          )
      )
  )

;Ejercicio 4
(define (nota)
  (define x 0)
  (display "Escribir la nota:")
  (set! x (read))
  (notas x)
  )

(define (notas x)
  (if (>= x 5)
      (begin (display "Exelente
")(display (* x 50)))
      (if (and(< x 5)(>= x 3))
          (begin (display "Buena
")(display (* x 20)))
          (if (< x 3)
              (begin (display "mala
")(display (* x 10)))
              (display"")
              )
          )
      )
  )

;Ejercicio 5
(define (paseo)
  (define x 0)
  (display "Escribir el numero de niños que iran al paseo:")
  (set! x (read))
  (niños x)
  )

(define (niños x)
  (if (<= x 10)
      (display (* x 3000))
      (if (and(> x 10)(<= x 50))
          (display (* x 2500))
          (if (and(> x 50)(<= x 200))
              (display (* x 2000))
              (if (> x 200)
                  (display (* x 1800))
                  (display "")
                  )
              )
          )
      )
  )

;Ejercicio 6
(define (libros)
  (define x 0)
  (display "Ingrese un numero: ")
  (set! x (read))
  (cond
   ((= x 1) (display"reproducir EL CAPITAL"))
   ((= x 2) (display"reproducir  EL CÓDIGO DA VINCI"))
   ((= x 3) (display"reproducir HARRY POTTER AND THE HALF BLOOD PRINCE"))
   ((= x 4) (display"reproducir CIEN AÑOS DE SOLEDAD"))
   ((= x 5) (display"reproducir LA ODISEA"))
   (else (display"Valor no valido"))
   )
  )

;Ejercicio 7
(define (interes)
  (define x 0)
  (display "valor de del deposito")
  (set! x (read))
  (display "Se gana un interes de:")
  (banco x)
  )

(define (banco x)
  (if (< x 30000)
      (* x 0.03)
      (if (< x 60000)
          (* x 0.05)
          (if (> x 60000)
              (* x 0.07)
              (display"")
              )
          )
      )
  )

;Ejercicio 8
(define (PlanVentas)
  (define x 0)
  (display "Peliculas a alquilar: ")
  (set! x (read))
  (display "Precio a pagar:")
  (peliculas x)
  )

(define (peliculas x)
  (if (<= x 5)
      (display(* x 3000))
      (if (and(> x 5)(<= x 10))
          (begin(display(* x 2500))(display"
Se le encima una pelicula a las ya compradas"))
          (if (and(> x 10)(<= x 15))
              (begin(display(* x 2000))(display"
Se le enciman dos peliculas a las ya compradas"))
              (if (> x 15)
                  (begin(display(* x 1800))(display"
Se le enciman tres peliculas a las ya compradas"))
                  (display"")
                  )
              )
          )
      )
  )

;Ejercicio 9
(define (partido)
  (define x 0)
  (display "Ingrese el numero de goles: ")
  (set! x (read))
  (cond
    ((= x 1) (display"Se salvo la honrilla"))
    ((and(> x 1)(<= x 3)) (display"Hazaña cafetera"))
    ((>= x 4) (display"¡Pereira, El mejor equipo del mundo!"))
    (else (display"Valor no valido"))
    )
  )

;Ejercicio 10
(define (vendedor)
  (define x 0)
  (display "Cuantas cuadras se recorrio en un dia: ")
  (set! x (read))

  (cond
    ((<= x 10) (- (* 20 3000)(*(* 20 3000)0.16)))
    ((and(>= x 11)(<= x 30))(- (* 60 3000)(*(* 60 3000)0.16)))
    ((and(>= x 31)(<= x 100))(- (* 80 3000)(*(* 80 3000)0.16))
                             )
    )
  )

;Ejercicio 11
(define (pagos)
  (define x 0)
  (display "Numero de horas trabajadas: ")
  (set! x (read))
  (display "Pago total: ")
  (display(pagototal x))
  (display "
Impuestos ganados: ")
  (display(impuesto2 (pagototal x)))
  (display "
Con un pago neto de: ")
  (display (pagoneto (pagototal x)))
  )
(define (impuesto2 x)
  (if (<= x 400000)
      (* x 0.00)
      (if (and(> x 400000)(< x 800000))
          (* x 0.15)
          (if (>= x 800000)
              (* x 0.28)
              (display "")
              )
          )
      )
  )
(define (pagoneto x)
  (if (<= x 400000)
      (- x (* x 0.00))
      (if (and(> x 400000)(< x 800000))
          (- x (* x 0.15))
          (if (>= x 800000)
              (- x(* x 0.28))
              (display "")
              )
          )
      )
  )
(define (pagototal x)
  (* x 20000)
  )

;Ejercicio 12
(define (musica)
  (define x 0)
  (display "Digite un numero: ")
  (set! x (read))
  (cond
    ((= x 1) (display"C:/Musica/RAP"))
    ((= x 2) (display"C:/Musica/HEAVY METAL"))
    ((= x 3) (display"C:/Musica/ROCK"))
    ((= x 4) (display"C:/Musica/REGGAETON"))
    ((= x 5) (display"C:/Musica/SALSA"))
    ((= x 6) (display"C:/Musica/VALLENATO"))
    (else (display "Valor no valido"))
    )
  )

;Ejercicio 13
(define (cuadratica)
  (define a 0)
  (define b 0)
  (define c 0)
  (display "Todas las ecuaciones cuadráticas (en una variable) tienen la siguiente forma general: a*x2+b*x+c=0
")
  (display "valor de a: ")  
  (set! a (read))
  (display "valor de b: ")  
  (set! b (read))
  (display "valor de c: ")  
  (set! c (read))
  (cond
    ((> (* b b) (* 4 a c)) (display"Tiene dos soluciones"))
    ((= (* b b) (* 4 a c)) (display"Tiene una solucion"))
    ((< (* b b) (* 4 a c)) (display"No tiene solucion"))
    )
  )

;Ejercicio 14
(define (juegos)
  (define x 0)
  (display "Digite un numero: ")
  (set! x (read))
  (cond
    ((= x 1) (display"JUEGA RESIDENT EVIL"))
    ((= x 2) (display"¡PONTE A DORMIR, YA!"))
    ((= x 3) (display"JUEGA WARCRAFT"))
    ((= x 4) (display"SOLO DEDÍCATE A BAILAR"))
    ((= x 5) (display"ESCUCHA MÚSICA"))
    ((= x 6) (display"VE AL CINE"))
    ((= x 7) (display"COMPRA 10 CERVEZAS Y ÉCHATE A VER FÚTBOL 5 HORAS"))
    (else (display "Valor no valido"))
    )
  )

;Ejercicio 15
(define(moneda)
  (define x 0)
  (display"Cantidad a apostar: ")
  (set! x (read))
  (loteria x)
      
  )
(define (loteria x)
  (define y (random 1 3))
  (cond
    ((= y 1)(* x 2))
    ((= y 2)(display"Mala suerte, sigue intentando."))
    )
  )

;Ejercicio 16
(define (entero)
  (define x 0)
  (display "Ingresar un numero entero: ")
  (set! x(read))
  (multiplos x)
  )
(define (multiplos x)
  (if(and(=(remainder x 2)0)(=(remainder x 5)0))
     (display"Es multiplo de 2 y 5")
     (if(and(=(remainder x 2)0) (not(=(remainder x 5)0)))
        (display"Solamente es multiplo de 2")
        (if(and(=(remainder x 5)0) (not(=(remainder x 2)0)))
           (display"Solamente es multiplo de 5")
           (display"")
           )
        )
     )
  
  )

;Ejercicio 17